
name: CI

on:
  [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          sudo apt install -y meson libx11-dev
          cp -R /usr/include/X11 include/
          cp -R /usr/include/xcb include/
          cp -R /usr/include/GL/* include/GL/
          pip3 install mako
          export ANDROID_NDK_HOME="$ANDROID_SDK_ROOT/ndk-bundle"
          # -Dglx=gallium-xlib \
          meson build-android-aarch64 \
            --prefix=/tmp/zink \
            --cross-file android-aarch64 \
            -Dplatforms=android \
            -Dplatform-sdk-version=25 \
            -Dandroid-stub=true \
            -Dllvm=disabled \
            -Dxlib-lease=disabled \
            -Degl=disabled \
            -Dglx=enabled \
            -Dgbm=disabled \
            -Dopengl=true \
            -Dvulkan-drivers= \
            -Dgallium-drivers=zink
          ## disable swrast for libGL fixme
          ninja -C build-android-aarch64 install
          cp build-android-aarch64/src/gallium/drivers/zink/libzink.a /tmp/zink/lib/

      - name: Upload libraries
        uses: actions/upload-artifact@v2
        with:
          name: libzink
          path: /tmp/zink
