
name: CI

on:
  [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          sudo apt install meson
          export ANDROID_NDK_HOME="$ANDROID_SDK_ROOT/ndk-bundle"
          meson build-android-aarch64 \
            --cross-file android-aarch64 \
            -Dplatforms=android \
            -Dplatform-sdk-version=24 \
            -Dandroid-stub=true \
            -Dgallium-drivers=zink
          ninja -C build-android-aarch64
