
name: CI

on:
  [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          sudo apt install meson
          pip3 install mako
          export ANDROID_NDK_HOME="$ANDROID_SDK_ROOT/ndk-bundle"
          #  --cross-file android-aarch64 \
          #  -Dplatform-sdk-version=25 \
          #  -Dandroid-stub=true \
          meson build-android-aarch64 \
            --prefix=/tmp/zink \
            -Dplatforms=x11 \
            -Dxlib-lease=disabled \
            -Degl=enabled \
            -Dgbm=disabled \
            -Dglx=disabled \
            -Dgles1=disabled \
            -Dgles2=disabled \
            -Dopengl=true \
            -Dvulkan-drivers= \
            -Dgallium-drivers=zink
          ninja -C build-android-aarch64 install
          cp build-android-aarch64/src/gallium/drivers/zink/libzink.a /tmp/zink/lib/

      - name: Upload libraries
        uses: actions/upload-artifact@v2
        with:
          name: libzink
          path: /tmp/zink
